# -*- coding: utf-8 -*-
"""get_random_regular_graph.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rlhWDPFJROGMeILeDMxFg4SUf7CEsd0y
"""

import networkx as nx                                              
import matplotlib.pyplot as plt 
import numpy as np
import scipy as sp

def store_undirected_network(A, N, path):
  f_out = open(path,'wt')
  for i in range(N-1):
    for j in range(i+1,N,1):
      if A[i,j] == 1:
        #print i+1,j+1
        f_out.write(str(i)+' '+str(j)+'\n')
  f_out.close()

N = 100;
q = 4 

path = 'random_regular'+str(N)+'_'+str(int(q))+'_adj.txt'

G = nx.random_regular_graph(q,N)
#Flag = nx.is_connected(G)
#print(Flag)

M = np.zeros((N,N), dtype=int)

Edge_list = nx.edges(G)
for edge in Edge_list:
  x = edge[0]
  y = edge[1]
  M[x-1][y-1] = 1
  M[y-1][x-1] = 1

store_undirected_network(M, N, path)